import express from 'express'
import cors from 'cors'

const app = express()
const PORT = 3002
const TRANSCRIPT_API = 'http://localhost:3003'

app.use(cors())
app.use(express.json())

// Fetch transcript via Python service
app.get('/api/transcript/:videoId', async (req, res) => {
  const { videoId } = req.params
  
  try {
    console.log(`Fetching transcript for: ${videoId}`)
    
    // Get transcript from Python service
    const transcriptResponse = await fetch(`${TRANSCRIPT_API}/transcript/${videoId}`)
    const transcriptData = await transcriptResponse.json()
    
    if (transcriptData.error) {
      // Try to get video info anyway
      const videoInfo = await fetchVideoInfo(videoId)
      return res.status(404).json({
        error: transcriptData.error,
        videoId,
        ...videoInfo
      })
    }
    
    // Get video info
    const videoInfo = await fetchVideoInfo(videoId)
    
    console.log(`✅ Got ${transcriptData.transcript?.length || 0} segments for ${videoId}`)
    
    res.json({
      videoId,
      ...videoInfo,
      language: transcriptData.language,
      isAutoGenerated: transcriptData.isAutoGenerated,
      transcript: transcriptData.transcript || []
    })
    
  } catch (error) {
    console.error('Error:', error.message)
    
    // Check if Python service is running
    if (error.cause?.code === 'ECONNREFUSED') {
      return res.status(503).json({ 
        error: 'Transcript service not running. Please start the Python transcript fetcher.',
        hint: 'Run: python3 transcript-fetcher.py'
      })
    }
    
    res.status(500).json({ error: error.message })
  }
})

// Fetch video info from YouTube oEmbed
async function fetchVideoInfo(videoId) {
  try {
    const oembedUrl = `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`
    const response = await fetch(oembedUrl)
    
    if (response.ok) {
      const data = await response.json()
      return {
        title: data.title,
        author: data.author_name,
        authorUrl: data.author_url,
        thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`
      }
    }
  } catch (e) {
    console.warn('Failed to fetch video info:', e.message)
  }
  
  return {
    title: `Video ${videoId}`,
    author: 'Unknown',
    thumbnail: `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`
  }
}

// Get video info endpoint
app.get('/api/video-info/:videoId', async (req, res) => {
  const { videoId } = req.params
  const info = await fetchVideoInfo(videoId)
  res.json({ videoId, ...info })
})

// Health check
app.get('/api/health', async (req, res) => {
  let transcriptServiceOk = false
  
  try {
    const healthCheck = await fetch(`${TRANSCRIPT_API}/health`)
    transcriptServiceOk = healthCheck.ok
  } catch (e) {
    // Service not running
  }
  
  res.json({
    status: 'ok',
    transcriptService: transcriptServiceOk ? 'ok' : 'not running'
  })
})

app.listen(PORT, () => {
  console.log(`✅ ClipSeeker API running at http://localhost:${PORT}`)
  console.log(`   Using transcript service at ${TRANSCRIPT_API}`)
  console.log('')
  console.log('   Make sure to start the Python transcript service:')
  console.log('   python3 transcript-fetcher.py')
})
